eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8767

spring:
  application:
    name: eshop-datalink-service
  redis:
    host: 192.168.1.207
    port: 1111